### ISSUE TITLE
Tx-queue MQTT topic

### ISSUE THREAD

**Issue by arjanvanderoest** [TheThingsNetwork/ttn#156]
Hi,

I would like to be able to track wether a downlink message has been removed from the queue and is actually transmitted and confirmed by the mote. Is it possible to add a MQTT topic that tracks this queue?

**Comment by htdvisser** [comment]
It would be possible to publish an "event" to MQTT whenever a message is removed from the queue (either because it is sent or when it expires). The second part (confirmation by the device) is something different: Confirmed Downlink.

I have created two separate issues for these features:

- #158 for supporting confirmed downlink
- #159 for supporting more events
