### ISSUE TITLE
Single faulty server breaks HTTP adapter

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#17]
Situation
===

* When HTTP adapter sends to a number of recipients 
* And one of those always returns 502 (for example)
* `adapter.go:67` adds an error and `adapter.go:93` returns an error, even when another server returned a normal response

Refs
===

1: [`adapter.go:67`](https://github.com/TheThingsNetwork/ttn/blob/develop/core/adapters/http/adapter.go#L67)
2: [`adapter.go:93`](https://github.com/TheThingsNetwork/ttn/blob/develop/core/adapters/http/adapter.go#L93)

**Comment by KtorZ** [comment]
Indeed, but, this does not interrupt the other sending. The send method will return an error because something goes wrong for one sending.
We have to work on how errors are declared and handled to get the best feedback possible but I don't feel like returning no error at all if one sending has issued an error, even if the other are okays. 

Incidentally, I'll dig into Docker, Github and Go built-in libraries to find some insights about how they  usually handle errors.
