### ISSUE TITLE
Is "Frames up" on TTN dashboard usful for tests, what is the update frequency?

### ISSUE THREAD

**Issue by EvertSchut** [TheThingsNetwork/ttn#201]
@htdvisser  Yesterday you saw packet coming in.  I used SendABP example scriptand I used modified OTAA example at that time after eachoter. Today I drove near Uithof for coverage, and the target was to find out wich script, or both, work. 

So to find out which script did the trick, I drove around with my Arduimo LoraOne om a suction holder outside my car window (thus using an external antenna outside the car) and ran both scipts. I never saw a join.  I was checking Frames up / Fcnt Up on the device's[dashboard](https://staging.thethingsnetwork.org/applications/70B3D57ED0000405/devices/0004A30B001B4A7E) and expected this number to grow as I got connection. After the tests we ditd yesterdag, it was grown from 204 to 435. But it is still at 435, so it seems I threw away 2 hours of drive tests. Or is this not a smart method? Is the Fcnt Up up only updataed every 12/24 hours or so? 

(1) What is the "Frames Up" of "Fcnt Up" update-interval, I mean the refresh time of this numer?
(2) And is this a good parameter/indication  to check wether  you are reaching TTN or not?

I also drove to Odijk were you saw packets come in, from 13:58 I used SendABP example script, after that, from 14:00-14:05 I used modified OTAA example. 
(3) Did you see packets, (4) when?

**Comment by EvertSchut** [comment]
I also drove to Odijk were you saw packets come in, from 13:58 I used ABB script, after 14:00 I used OTAA example. Did you see packets, when?

**Comment by htdvisser** [comment]
I'm sorry, but I don't have the time to go through the server logs every time to check if your node is working.

The dashboard receives live updates when the frame counter increases and updates it immediately. I suggest you read [this information about frame counters](http://staging.thethingsnetwork.org/wiki/LoRaWAN/Security#security-in-lorawan-and-ttn_frame-counters), as it explains why your counters are not increasing.

Also I think it's better to ask these kind of questions on [Slack](http://slack.thethingsnetwork.org/) instead of creating issues here on Github. This way, we can use Github for real issues that are related to the implementation of The Things Network.
