### ISSUE TITLE
[MQTT] Include AppID and DevID in payloads

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/ttn#241]
See https://www.thethingsnetwork.org/docs/refactor/mqtt/#topic-activations for the current (refactor) payloads. For both activations and messages, the `app_id` and `dev_id` are not in the payloads.

They are in the part of the published topic path of course, but as the [Node.js library](https://github.com/TheThingsNetwork/node-app-lib/blob/master/src/client.js#L39-L40) demonstrates, this requires the consumer to filter these values out of the path.

We should include `app_id` and `dev_id` in the payload itself so you can read them directly and write less code.

**Note:** Yes, for `app_id` this is less important because you already authenticate and subscribe with it, but.. you might very well want to pass on or store the payload somewhere unaware of this context, in which case you'd need to append the `app_id` as well.

**Comment by johanstokking** [comment]
I'm not in favor of adding these fields to the payload. This is redundant as they are in the topic. The topic is the key identifier on MQTT, and payload should only contain data.

I'm aware that it is easier to handle because users don't have to split the topic themselves when they use MQTT directly. However, if they're used to MQTT, they do this already, and if they're not used to MQTT, they can use a library (Go, Node.js, Java, more to come) that does it for them.
