### ISSUE TITLE
Handle retries for confirmed uplinks

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#272]
![556c49e4b31d4c287ab6ad371c47f322aaa53144](https://cloud.githubusercontent.com/assets/181308/18846128/c83f87a8-8424-11e6-85ca-fbc28fa7a277.png)

**Comment by matthijskooijman** [comment]
```
16:35 <htdvisser> There is one issue with confirmed uplink though, but in my opinion that's more a flaw in LoRaWAN itself. When a device does not receive an ACK to a confirmed uplink, it sends the message again (which is okay) with the same frame counter (which I think is wrong). The backend flags this as a possible replay attack, and will therefore ignore the message
18:17 <matthijs> htdvisser: Shouldn't it just drop the message *and* send an ACK?
18:45 <htdvisser> @matthijs: please comment on Github Issue so that this doesn't get lost in Slack historyhttps://github.com/TheThingsNetwork/ttn/issues/272 
```

**Comment by avbentem** [comment]
> When a device does not receive an ACK to a confirmed uplink, it sends the message again (which is okay) with the same frame counter (which I think is wrong).

I guess an increased uplink frame counter would be troublesome as then backend and application would not even know they got a retry.

Just FYI, when fixing this: note that the image shows that the backend should use an increased downlink counter `{Cd+1}` when confirming the retry.

**Comment by matthijskooijman** [comment]
Indeed, if the ACK went missing but the original upstream packet was received ok, the application will receive the same data twice. This is not a problem for timestamped sensor data, but for a data stream or otherwise non-idempotent data, this would force the application to add their own sequencing / frame counters into the data, which seems counter-productive.
