### ISSUE TITLE
Add ExchangeDeclarePassive to AMQP in Handler

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/ttn#353]
The Handler currently panicks when started with Docker

```
FATAL Could not initialize handler             error=Failed to bind queue ttn-handler-downlink with key *.devices.*.down on exchange 'ttn.handler' (Exception (404) Reason: "NOT_FOUND - no exchange 'ttn.handler' in vhost '/'")
```

This can be easily avoided by calling `ExchangeDeclarePassive` to declare the exchange if it doesn't exist yet.

**Comment by johanstokking** [comment]
Yes, note that this needs the Handler to have permissions to declare exchanges. Might be fine for now, but we might choose for an elevated initialization process that sets up and migrates the environment, so that the actual components that have external interfaces (like the Handler), only have the rights that they actually need. Should the Handler, or other components with many permissions, get compromised, the impact is limited because of limited permissions.

**Comment by htdvisser** [comment]
Isn't this exactly what ExchangeDeclarePassive is for? From the docs: `it sets the "passive" attribute to true. A passive exchange is assumed by RabbitMQ to already exist, and attempting to connect to a non-existent exchange will cause RabbitMQ to throw an exception. This function can be used to detect the existence of an exchange.`

**Comment by johanstokking** [comment]
Yes that is what it's for, but my point is that the Handler should not have privileges to declare exchanges in the first place. It's not only using `ExchangeDeclarePassive`, which is fine in itself, but it should be an indicator to the user to declare the exchange out of band, or deliberately change the Handler's configuration to use a privileged account.

**Comment by htdvisser** [comment]
I believe it's important to help contributors get started as smoothly as possible. This is also the reason why we have development keys and certificates in the repository. Setting up accounts with correct privileges is something we should document for the setup of production environments, but for development, I really believe that people should be able to get started with one keypress.
