### ISSUE TITLE
Remove scheduled downlink

### ISSUE THREAD

**Issue by sukoy** [TheThingsNetwork/ttn#697]
Hi!

There is a way to remove a scheduled downlink from queue?
Our devices use OTAA and after reset cnt goes to 0, is there a way to remove previous scheduled downlink? to avoid twice received message.

Thanks

**Comment by johanstokking** [comment]
@sukoy atm there's no way to clear the queue, apart from replacing it with a new value. This will be added in V3.

**Comment by sukoy** [comment]
ok Thanks

**Comment by haorfani** [comment]
I am still having trouble with this issue. If I schedule a downlink message from an application, it is sent forever. Is there a way to stop it?

**Comment by johanstokking** [comment]
@haorfani that should not happen. Are you sending confirmed downlink and is the downlink not confirmed by the end device, by chance? Because in that case it works as expected.

**Comment by haorfani** [comment]
By this you mean that the end device should send a ACK packet back to the GW right?

**Comment by haorfani** [comment]
OK I fixed it, it was my own bug after all. Thanks for the response though!

**Comment by pradeeka7** [comment]
I have the same issue with my RAKwireless 7205 tracker. This happened from the second day. First day it worked well. I haven't yet restarted the tracker.

I'm sending UNCONFIRMED messages. I can't send confirmed messages because the latest firmware has a bug (I guess).

![image](https://user-images.githubusercontent.com/36432168/85216984-fa185e00-b3a8-11ea-8e41-14bfd19d292d.png)

**Comment by jpmeijers** [comment]
Downlinks on port 0 are mac commands. Most likely what you are seeing is the ADR downlinks telling your device to go to a faster datarate and/or lower output power.
